version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: | 
              echo "Hello, world (test fork ci, add env variable)."
              echo "test22 ${VARIABLE_TEST}"

      - run:
          name: Print the Current Time
          command: date
