version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: |
              if [ -n "$CIRCLE_PR_NUMBER" ]; then
                  echo "Nothing to do for forked PRs, so marking this step successful"
                  circleci step halt
              fi 
              echo "${CIRCLE_PR_NUMBER}"
              echo "Hello, world (test fork ci, add env variable)."
              echo "test2 ${VARIABLE_TEST}"

      - run:
          name: Print the Current Time
          command: date
