version: 2.1

executors:
  infrastructure_container_unstable:
    docker:
      - image: aeternity/infrastructure:latest

references:
  master_branch: &master_branch master

jobs:
 integration_sync:
   executor: infrastructure_container_unstable
   steps:
     - checkout
     - run:
         name: Integration sync
         command: |
           cd /infrastructure && DEPLOY_ENV=integration_sync make mnesia-reset-once

workflows:
  version: 2

  integration_sync:
    triggers:
      - schedule:
          # run at midnight and noon UTC
          cron: "0 0,12 * * *"
          filters:
            branches:
              only:
                - *master_branch
    jobs:
      - integration_sync:
          context: ae-node-builds
