<?php

namespace Blog\PostBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findAllByTag($tagId)
    {
        $posts = $this
            ->createQueryBuilder('p')
            ->select('p, t')
            ->leftJoin('p.tags', 't')
            ->where("t.id = :tag")
            ->setParameter('tag', $tagId)
            ->orderBy('p.date', 'DESC')
            ->getQuery();

        return $posts;
    }

    public function findAllOrderedByDate()
    {
         $posts = $this
            ->createQueryBuilder('p')
            ->select('p')
            ->orderBy('p.date', 'DESC')
            ->getQuery();

        return $posts;
    }

    public function findAllCommentsUser($user)
    {
        $post = $this
            ->createQueryBuilder('p')
            ->select('p, c')
            ->leftJoin('p.posts_id', 'c')
            ->where('c.user_id = :user')
            ->setParameter('user', $user)
            ->getQuery();

        var_dump($post);
        exit;
        return $post;
    }
}
